### ISSUE TITLE
Error with the requirements.txt

### ISSUE THREAD

**Issue by fgrellar** [DBJoran/Shinyhunter#6]
Hello,

When I try to install the requirements it's look like some version doesn't exist and when I install everything by hand with the last version I need and in in predictor I need to import joblib without the from and also it's look like sklearn.ensemble.bagging doesn't exist

**Comment by DBJoran** [comment]
Hey,

Sorry for the late reply.
I have not worked on this project for a while. The requirements.txt is a mess at the moment and includes a lot of dependencies that are not required. 

When I have some spare time I will try to reproduce your issue and clean up the requirements.txt

**Comment by DBJoran** [comment]
I'm gonna close this issue, the current .joblib is outdated and can't be used anymore. I will stop doing the OCR with Sklearn and replace it will something else, possibly Template Matching with OpenCV.
